const AnnotationConstants = {
  ANNOTATION_REVEALED: "ANNOTATION_REVEALED",
  ANNOTATION_REMOVED: "ANNOTATION_REMOVED",
  ANNOTATION_CREATED: "ANNOTATION_CREATED",
  ANNOTATION_DELETED: "ANNOTATION_DELETED",
  ANNOTATION_UPDATED: "ANNOTATION_UPDATED"
};

module.exports = AnnotationConstants;
