const AnnotationConstants = {
  ANNOTATION_REVEALED: "ANNOTATION_REVEALED",
  ANNOTATION_REMOVED: "ANNOTATION_REMOVED",
  ANNOTATION_CREATED: "ANNOTATION_CREATED"
};

module.exports = AnnotationConstants;
